var actionIcons = [  
  {  
    "class_name":"sprite-accept",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-accept_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-account_split",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-account_split_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-account_split_edit",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-add",
    "description":"",
    "usage":"",
    "notes":"This also means ADD NEW"
  },
  {  
    "class_name":"sprite-add_bw",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-add_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-amendment",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-amount_deliverable",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-anchor",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-application-form",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-application_form",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-application_form_delete",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-application_view_detail",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-applications-blue",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-approved",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_down_gray",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_left",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_left_gray",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_refresh",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_right",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_right_gray",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_rotate_right",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_split",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_undo",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_undo_bw",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_up_gray",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_void",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-asterisk_orange",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-attach",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-basket",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-bell",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-bell_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-bell_remove",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-black_star",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-blank_box",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-briefcase",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-bullet_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-bullseye",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-calculator",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-calendar_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cart_delete",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cart_edit",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cart_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cart_put",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-chart_organisation",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-chart_organisation_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-check-gray",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-checkbox",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-checkbox-disabled",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-checkbox-selected",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-circled-checkmark",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-clipboard",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cog",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cog_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-coins",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-coins_cn",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-collapsable",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-collapsed_section",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-comment",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-comment_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-comment_transparent",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-connect",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-connecting",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract-changed-flag",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_approved",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_completed",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_draft",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_pending_approval",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_pending_signatures",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_published",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_approved",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_completed",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_draft",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_expired",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_pending_approval",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_pending_signatures",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_published",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_approved",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_completed",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_draft",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_expired",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_pending_approval",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_pending_signatures",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_published",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-coupa-advantage",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-create_ro",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-creditcards",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cross",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cross_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cycle_back",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-delete",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-delete",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-delete_bw",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-delete_large",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-delete_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-disabled",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-disk",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-disk_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-door_in",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-drag_handle",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-email",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-email_blocked",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-email_edit",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-email_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-email_go_bw",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-email_open",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-enabled",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-error",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-escalated",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-exclamation",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-existing-relationships",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-expanded_section",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-external_update",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-field-changed-flag",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-folder_open",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-gauge",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-grid",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-group",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-health_rating0",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-health_rating1",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-health_rating2",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-health_rating3",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-inbox-move",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-info",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-info_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-internal_update",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-invisible",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-invoicesmash",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-items_not_in_lots",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-key_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-keyboard",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-layers",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lightning_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lines",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-link",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-list",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lock",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lock_blue",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lock_break",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lock_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lock_gray",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lorry",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lorry_bw",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-magic",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-magic_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-magnifier",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-magnifier_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-magnifier_small_grey",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-magnifier_small_grey",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-master",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-medal_gold_3",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-minus",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-money",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-money_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-msa",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-no",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-no_self_approval_allowed",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-note",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-operational-insights",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-package",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-package_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-page_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-page_blank",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-page_code",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-page_copy",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-page_copy_bw",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-page_excel",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-page_white_acrobat",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-page_word",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-pencil",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-pencil_bw",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-pencil_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-pending_approval",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-po-for-wc",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-po-invoice-stop",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-po-release-invoice-stop",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-po-reopen",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-po-soft-close",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-pop-out",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-price_tier",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-printer",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-printer_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-quantity_deliverable",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-red-flag",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-request_review",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-resource",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-restore",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-searchable-punchout",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-ship-to",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-sourcing",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-stop",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-supplier-item-association",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-supplier-items-explorer",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-table",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-table_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-table_sort",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tag_blue",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tag_blue_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tag_blue_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tag_red",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-thumb_up",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tick",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tick-gray",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-time",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-transmit",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tripit",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-twitter",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-upgrade",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user_comment",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user_green",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user_w",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-vertical_split",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-vertical_split_edit",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-visible",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-wand",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-white_star",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-world_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-wrench",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-zoom",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-zoom_in",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-zoom_out",
    "description":"",
    "usage":"",
    "notes":""
  }
];
