var actionIcons = [  
  {  
    "class_name":"sprite-accept",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-accept_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-account_split",
    "description":"",
    "usage":"Billing Account",
    "notes":""
  },
  {  
    "class_name":"sprite-account_split_add",
    "description":"",
    "usage":"Billing Account",
    "notes":""
  },
  {  
    "class_name":"sprite-account_split_edit",
    "description":"",
    "usage":"Billing Account",
    "notes":""
  },
  {  
    "class_name":"sprite-add",
    "description":"",
    "usage":"Add New",
    "notes":""
  },
  {  
    "class_name":"sprite-add_bw",
    "description":"",
    "usage":"Add New Disabled",
    "notes":""
  },
  {  
    "class_name":"sprite-add_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-amendment",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-amount_deliverable",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-anchor",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-application-form",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-application_form",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-application_form_delete",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-application_view_detail",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-applications-blue",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-approved",
    "description":"",
    "usage":"Done, Approved, Completed",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_down_gray",
    "description":"",
    "usage":"Use to expand, collapse, scroll to the Left or right in sections and dashboards",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_left",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_left_gray",
    "description":"",
    "usage":"Use to expand, collapse, scroll to the Left or right in sections and dashboards",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_refresh",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_right",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_right_gray",
    "description":"",
    "usage":"Use to expand, collapse, scroll to the Left or right in sections and dashboards",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_rotate_right",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_split",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_undo",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_undo_bw",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_up_gray",
    "description":"",
    "usage":"Use to expand, collapse, scroll to the Left or right in sections and dashboards",
    "notes":""
  },
  {  
    "class_name":"sprite-arrow_void",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-asterisk_orange",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-attach",
    "description":"",
    "usage":"Attachment",
    "notes":""
  },
  {  
    "class_name":"sprite-basket",
    "description":"",
    "usage":"Item",
    "notes":""
  },
  {  
    "class_name":"sprite-bell",
    "description":"",
    "usage":"Alert",
    "notes":""
  },
  {  
    "class_name":"sprite-bell_add",
    "description":"",
    "usage":"Alert",
    "notes":""
  },
  {  
    "class_name":"sprite-bell_remove",
    "description":"",
    "usage":"Alert",
    "notes":""
  },
  {  
    "class_name":"sprite-black_star",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-blank_box",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-briefcase",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-bullet_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-bullseye",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-calculator",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-calendar_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cart_delete",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cart_edit",
    "description":"",
    "usage":"Adjust Inventory Balance",
    "notes":""
  },
  {  
    "class_name":"sprite-cart_go",
    "description":"",
    "usage":"Transfer Inventory Balance",
    "notes":""
  },
  {  
    "class_name":"sprite-cart_put",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-chart_organisation",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-chart_organisation_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-check-gray",
    "description":"",
    "usage":"Accept Disabled",
    "notes":""
  },
  {  
    "class_name":"sprite-checkbox",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-checkbox-disabled",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-checkbox-selected",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-circled-checkmark",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-clipboard",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cog",
    "description":"",
    "usage":"Settings",
    "notes":""
  },
  {  
    "class_name":"sprite-cog_go",
    "description":"",
    "usage":"Settings",
    "notes":""
  },
  {  
    "class_name":"sprite-coins",
    "description":"",
    "usage":"Invoice",
    "notes":""
  },
  {  
    "class_name":"sprite-coins_cn",
    "description":"",
    "usage":"Credit Note",
    "notes":""
  },
  {  
    "class_name":"sprite-collapsable",
    "description":"",
    "usage":"Use to expand, collapse, scroll to the Left or right in sections and dashboard",
    "notes":""
  },
  {  
    "class_name":"sprite-collapsed_section",
    "description":"",
    "usage":"Use to expand, collapse, scroll to the Left or right in sections and dashboard",
    "notes":""
  },
  {  
    "class_name":"sprite-comment",
    "description":"",
    "usage":"Comment",
    "notes":""
  },
  {  
    "class_name":"sprite-comment_add",
    "description":"",
    "usage":"Comment",
    "notes":""
  },
  {  
    "class_name":"sprite-comment_transparent",
    "description":"",
    "usage":"Comment",
    "notes":""
  },
  {  
    "class_name":"sprite-connect",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-connecting",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-contract",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract-changed-flag",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_approved",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_completed",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_draft",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_pending_approval",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_pending_signatures",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_amendment_published",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_approved",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_completed",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_draft",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_expired",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_pending_approval",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_pending_signatures",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_child_published",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_approved",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_completed",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_draft",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_expired",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_pending_approval",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_pending_signatures",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-contract_parent_published",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-coupa-advantage",
    "description":"",
    "usage":"Coupa Advantage logo or type",
    "notes":""
  },
  {  
    "class_name":"sprite-create_ro",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-creditcards",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-cross",
    "description":"",
    "usage":"Delete",
    "notes":""
  },
  {  
    "class_name":"sprite-cross_small",
    "description":"",
    "usage":"Delete",
    "notes":""
  },
  {  
    "class_name":"sprite-cycle_back",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-delete",
    "description":"",
    "usage":"Delete",
    "notes":""
  },
  {  
    "class_name":"sprite-delete",
    "description":"",
    "usage":"Delete",
    "notes":""
  },
  {  
    "class_name":"sprite-delete_bw",
    "description":"",
    "usage":"Delete Disabled",
    "notes":""
  },
  {  
    "class_name":"sprite-delete_large",
    "description":"",
    "usage":"Delete",
    "notes":""
  },
  {  
    "class_name":"sprite-delete_small",
    "description":"",
    "usage":"Delete",
    "notes":""
  },
  {  
    "class_name":"sprite-disabled",
    "description":"",
    "usage":"Disabled, hidden, not visible, inactive, non-active",
    "notes":""
  },
  {  
    "class_name":"sprite-disk",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-disk_small",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-door_in",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-drag_handle",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-email",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-email_blocked",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-email_edit",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-email_go",
    "description":"",
    "usage":"Send, submit",
    "notes":""
  },
  {  
    "class_name":"sprite-email_go_bw",
    "description":"",
    "usage":"Send, submit",
    "notes":""
  },
  {  
    "class_name":"sprite-email_open",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-enabled",
    "description":"",
    "usage":"Enabled, viewable, visible, active",
    "notes":""
  },
  {  
    "class_name":"sprite-error",
    "description":"",
    "usage":"Error, alert",
    "notes":""
  },
  {  
    "class_name":"sprite-escalated",
    "description":"",
    "usage":"Escalated, approvals",
    "notes":""
  },
  {  
    "class_name":"sprite-exclamation",
    "description":"",
    "usage":"Error, alert",
    "notes":""
  },
  {  
    "class_name":"sprite-existing-relationships",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-expanded_section",
    "description":"",
    "usage":"Use to expand, collapse, scroll to the Left or right in sections and dashboards",
    "notes":""
  },
  {  
    "class_name":"sprite-external_update",
    "description":"",
    "usage":"Send, submit",
    "notes":""
  },
  {  
    "class_name":"sprite-field-changed-flag",
    "description":"",
    "usage":"Flag",
    "notes":""
  },
  {  
    "class_name":"sprite-folder_open",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-gauge",
    "description":"",
    "usage":"Accelerate, Coupa Accelerate",
    "notes":""
  },
  {  
    "class_name":"sprite-grid",
    "description":"",
    "usage":"In data table view buttons to switch from lines to card view",
    "notes":""
  },
  {  
    "class_name":"sprite-group",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-health_rating0",
    "description":"",
    "usage":"Supplier Health No Data Available",
    "notes":""
  },
  {  
    "class_name":"sprite-health_rating1",
    "description":"",
    "usage":"Supplier Health High Risk",
    "notes":""
  },
  {  
    "class_name":"sprite-health_rating2",
    "description":"",
    "usage":"Supplier Health Trusted",
    "notes":""
  },
  {  
    "class_name":"sprite-health_rating3",
    "description":"",
    "usage":"Supplier Health Best in Class",
    "notes":""
  },
  {  
    "class_name":"sprite-inbox-move",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-info",
    "description":"",
    "usage":"Information, Help",
    "notes":""
  },
  {  
    "class_name":"sprite-info_add",
    "description":"",
    "usage":"Information, Help",
    "notes":""
  },
  {  
    "class_name":"sprite-internal_update",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-invisible",
    "description":"",
    "usage":"Invisible, disabled, inactive",
    "notes":""
  },
  {  
    "class_name":"sprite-invoicesmash",
    "description":"",
    "usage":"Invoicing, Invoice Smash",
    "notes":""
  },
  {  
    "class_name":"sprite-items_not_in_lots",
    "description":"",
    "usage":"Sourcing, Items not in Lots",
    "notes":""
  },
  {  
    "class_name":"sprite-key_go",
    "description":"",
    "usage":"Setup, Users, Reset Password",
    "notes":""
  },
  {  
    "class_name":"sprite-keyboard",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-layers",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lightning_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lines",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-link",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-list",
    "description":"",
    "usage":"In data table view buttons to switch from lines to card view",
    "notes":""
  },
  {  
    "class_name":"sprite-lock",
    "description":"",
    "usage":"Locked",
    "notes":""
  },
  {  
    "class_name":"sprite-lock_blue",
    "description":"",
    "usage":"Locked",
    "notes":""
  },
  {  
    "class_name":"sprite-lock_break",
    "description":"",
    "usage":"Locked",
    "notes":""
  },
  {  
    "class_name":"sprite-lock_go",
    "description":"",
    "usage":"Locked",
    "notes":""
  },
  {  
    "class_name":"sprite-lock_gray",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-lorry",
    "description":"",
    "usage":"Receive",
    "notes":""
  },
  {  
    "class_name":"sprite-lorry_bw",
    "description":"",
    "usage":"Receive",
    "notes":""
  },
  {  
    "class_name":"sprite-magic",
    "description":"",
    "usage":"Split Billing",
    "notes":""
  },
  {  
    "class_name":"sprite-magic_add",
    "description":"",
    "usage":"Split Billing",
    "notes":""
  },
  {  
    "class_name":"sprite-magnifier",
    "description":"",
    "usage":"Search",
    "notes":""
  },
  {  
    "class_name":"sprite-magnifier_small",
    "description":"",
    "usage":"Search",
    "notes":""
  },
  {  
    "class_name":"sprite-magnifier_small_grey",
    "description":"",
    "usage":"Search Disabled",
    "notes":""
  },
  {  
    "class_name":"sprite-magnifier_small_grey",
    "description":"",
    "usage":"Search Disabled",
    "notes":""
  },
  {  
    "class_name":"sprite-master",
    "description":"",
    "usage":"Contracts",
    "notes":""
  },
  {  
    "class_name":"sprite-medal_gold_3",
    "description":"",
    "usage":"Award",
    "notes":""
  },
  {  
    "class_name":"sprite-minus",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-money",
    "description":"",
    "usage":"Service",
    "notes":""
  },
  {  
    "class_name":"sprite-money_add",
    "description":"",
    "usage":"Search Disabled",
    "notes":""
  },
  {  
    "class_name":"sprite-msa",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-no",
    "description":"",
    "usage":"Not Enabled, missing, not available",
    "notes":""
  },
  {  
    "class_name":"sprite-no_self_approval_allowed",
    "description":"",
    "usage":"Lock",
    "notes":""
  },
  {  
    "class_name":"sprite-note",
    "description":"",
    "usage":"Note, Add Note",
    "notes":""
  },
  {  
    "class_name":"sprite-operational-insights",
    "description":"",
    "usage":"Tertiary Header Icon Operationa Insights",
    "notes":""
  },
  {  
    "class_name":"sprite-package",
    "description":"",
    "usage":"Detail Receive",
    "notes":""
  },
  {  
    "class_name":"sprite-package_add",
    "description":"",
    "usage":"Detail Receive",
    "notes":""
  },
  {  
    "class_name":"sprite-page_add",
    "description":"",
    "usage":"Add Bid, Act as Supplier to add bid",
    "notes":""
  },
  {  
    "class_name":"sprite-page_blank",
    "description":"",
    "usage":"Document",
    "notes":""
  },
  {  
    "class_name":"sprite-page_code",
    "description":"",
    "usage":"Document",
    "notes":""
  },
  {  
    "class_name":"sprite-page_copy",
    "description":"",
    "usage":"Copy",
    "notes":""
  },
  {  
    "class_name":"sprite-page_copy_bw",
    "description":"",
    "usage":"Copy Disabled",
    "notes":""
  },
  {  
    "class_name":"sprite-page_excel",
    "description":"",
    "usage":"Document",
    "notes":""
  },
  {  
    "class_name":"sprite-page_white_acrobat",
    "description":"",
    "usage":"Document",
    "notes":""
  },
  {  
    "class_name":"sprite-page_word",
    "description":"",
    "usage":"Document",
    "notes":""
  },
  {  
    "class_name":"sprite-pencil",
    "description":"",
    "usage":"Edit",
    "notes":""
  },
  {  
    "class_name":"sprite-pencil_bw",
    "description":"",
    "usage":"Edit",
    "notes":""
  },
  {  
    "class_name":"sprite-pencil_small",
    "description":"",
    "usage":"Edit",
    "notes":""
  },
  {  
    "class_name":"sprite-pending_approval",
    "description":"",
    "usage":"Pending Approval",
    "notes":""
  },
  {  
    "class_name":"sprite-po-for-wc",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-po-invoice-stop",
    "description":"",
    "usage":"Stop Invoice",
    "notes":""
  },
  {  
    "class_name":"sprite-po-release-invoice-stop",
    "description":"",
    "usage":"Release Invoice Hold",
    "notes":""
  },
  {  
    "class_name":"sprite-po-reopen",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-po-soft-close",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-pop-out",
    "description":"",
    "usage":"Full screen, pop out as a separate window",
    "notes":""
  },
  {  
    "class_name":"sprite-price_tier",
    "description":"",
    "usage":"Tiered Pricing",
    "notes":""
  },
  {  
    "class_name":"sprite-printer",
    "description":"",
    "usage":"Print",
    "notes":""
  },
  {  
    "class_name":"sprite-printer_small",
    "description":"",
    "usage":"Print",
    "notes":""
  },
  {  
    "class_name":"sprite-quantity_deliverable",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-red-flag",
    "description":"",
    "usage":"Flag",
    "notes":""
  },
  {  
    "class_name":"sprite-request_review",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-resource",
    "description":"",
    "usage":"Resource, human",
    "notes":""
  },
  {  
    "class_name":"sprite-restore",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-searchable-punchout",
    "description":"",
    "usage":"Searchable Punchout",
    "notes":""
  },
  {  
    "class_name":"sprite-ship-to",
    "description":"",
    "usage":"Ships to, ship to countires, ship to areas",
    "notes":""
  },
  {  
    "class_name":"sprite-sourcing",
    "description":"",
    "usage":"Sourcing, Source This, Send to RFQ",
    "notes":""
  },
  {  
    "class_name":"sprite-stop",
    "description":"",
    "usage":"Invoice Hold",
    "notes":""
  },
  {  
    "class_name":"sprite-supplier-item-association",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-supplier-items-explorer",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-table",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-table_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-table_sort",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tag_blue",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tag_blue_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tag_blue_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tag_red",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-thumb_up",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tick",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tick-gray",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-time",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-transmit",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-tripit",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-twitter",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-upgrade",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user_add",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user_comment",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user_green",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-user_w",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-vertical_split",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-vertical_split_edit",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-visible",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-wand",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-white_star",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-world_go",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-wrench",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-zoom",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-zoom_in",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"sprite-zoom_out",
    "description":"",
    "usage":"",
    "notes":""
  }
];
