var headerIcons = [
  {
    "class_name":"header-additional-settings",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-address",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-alerts",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-approval",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-attachments",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-benchmark-efficiency",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-benchmark-savings",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-benchmark-usage",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-budgets",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-business-partner",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-buyOnline",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-cart",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-chat",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-clipboard",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-comments",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-compare",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-competitive-chart",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-completed-recommendations",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-content-groups",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-contract-details",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-contracts",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-credit_card",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-cxml",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-documents",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-event-details",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-event-items-and-lots",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-event-questionnaires",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-event-timeline",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-event-type",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-financials",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-groups-and-tasks",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-history",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-info",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-invoice-inbox",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-invoicing",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-items",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-lines",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-message",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-payments",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-pending-recommendations",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-performance-management",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-po-transmission",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-pricing-and-terms",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-recentOrders",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-reportHeader",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-reportsHeader",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-requisitions",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-responses",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-score-weights",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-services",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-shipping",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-suitcase_white",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-supplier",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-supplier-details",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-supplier-rating",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-terms-and-conditions",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-timesheet",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-toDos",
    "description":"",
    "usage":"",
    "notes":""
  },
  {  
    "class_name":"header-with-status",
    "description":"",
    "usage":"",
    "notes":""
  }
];